name: Build executable for macOS
# Executes every time something is tagged to the main branch
# WARNING: if your DockerHub or GitHub user name contains capital letters
# the image push will fail, since only lower letters are allowed!
on:
  push:
    tags:
        - '*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run electron-build
      - name: Pack
        run: electron-packager . --platform=darwin
      - name: zip
        run: zip -r totp-manager.zip totp-manager-darwin-x64/totp-manager.app
      - name: Create new release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload macOS artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: totp-manager.zip
          asset_name: totp-manager_macOS.zip
          asset_content_type: application/zip
