name: Publish Docker image to GitHub container registry
# Executes every time something is tagged to the main branch
# WARNING: if your DockerHub or GitHub user name contains capital letters
# the image push will fail, since only lower letters are allowed!
on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_HUB_CR_KEY }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push
        run: |
          docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/docker-cicd:latest
          docker push ghcr.io/${{ github.actor }}/docker-cicd:latest 